services:
  samba:
    build: .
    container_name: samba
    ports:
      - "139:139"
      - "445:445"
    volumes:
      - ./mount:/mount
      - ./config/smb.conf:/etc/samba/smb.conf
    env_file:
      - .env
    environment:
      - TZ=America/Sao_Paulo
    restart: unless-stopped
